### ISSUE TITLE
No results after benchmark

### ISSUE THREAD

**Issue by narduin** [http2benchmark/http2benchmark#14]
Hello.

I'm trying to run some benchmarks.
I have two ubuntu 20.04 servers and everytime I launch a benchmark I get this error after it's completed:

```bash
Benchmark testing ------End------
***Total of 282 seconds to finish process***
No result, skip!
[FAILED] to generate RESULTS.csv
#############  Benchmark Result  #################
h2load-h1	 --h1 -n 100000 -c 100 -t 1 -T 30 -m 1 -H  'Accept-Encoding: gzip,deflate' https://benchmark.com/1knogzip.jpg
cat: /opt/h2bench/Benchmark/102320-170121/RESULTS.csv: No such file or directory
```

The .log files are inside /opt/h2bench/Benchmark/TIMESTAMPS/SERVER but there are no results.

Thanks!

**Comment by http2benchmark** [comment]
It should have been fixed, please try again.

**Comment by narduin** [comment]
It works now, thanks!
