### ISSUE TITLE
openlitespeed conf override litespeed ?

### ISSUE THREAD

**Issue by centminmod** [http2benchmark/http2benchmark#5]
From commit at https://github.com/http2benchmark/http2benchmark/commit/8c74bb27a2fb49057a4a48c4edc03514b280d08c it seems openlitespeed is installed into same directory as litespeed on centos 7 at /usr/local/lsws ? How does that work exactly as server.sh complains in `cpuprocess` function that sed replacement file `${OLSDIR}/conf/httpd_config.xml` does not exist ? I see /usr/local/lsws/conf/httpd_config.conf file instead after latest server.sh runs when both litespeed and then openlitespeed are installed ?

```
ls -lah /usr/local/lsws/conf/
total 72K
drwxr-xr-x  5 lsadm lsadm 4.0K Aug 11 09:41 .
drwxr-xr-x 21 root  root  4.0K Aug 11 09:40 ..
drwxr-xr-x  2 lsadm lsadm    6 Jul 15 19:17 cert
-rw-r--r--  1 lsadm lsadm 6.0K Aug 11 09:41 httpd_config.conf
-rw-------  1 lsadm lsadm 6.0K Aug 11 09:34 httpd_config.conf0
-r--------  1 lsadm lsadm  14K Aug 11 09:34 httpd_config.conf0,v
-rw-------  1 lsadm lsadm 7.5K Jul 15 19:17 httpd_config.conf_old
-rwxr-xr-x  1 lsadm lsadm 4.9K Jul 15 19:17 mime.properties
-rwxr-xr-x  1 lsadm lsadm 4.9K Aug 11 09:26 mime.properties0
-r-xr-xr-x  1 lsadm lsadm 5.1K Aug 11 09:26 mime.properties0,v
drwxr-xr-x  2 lsadm lsadm  110 Aug 11 09:40 templates
drwxr-xr-x  3 lsadm lsadm   20 Jul 15 19:17 vhosts
```
```
cat /usr/local/lsws/VERSION 
1.4.49
```

**Comment by http2benchmark** [comment]
should be fixed with 
94bdeb714bbe7e4fcf7ebd154497fd8bb9fc37b5

**Comment by centminmod** [comment]
cheers :)
